name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2

      - name: 'Set up JDK 15'
        uses: actions/setup-java@v1
        with:
          java-version: 15-ea

      - name: 'Build with Bach.java'
        run: jshell https://sormuras.de/bach/build

      - name: 'Store logbook in build artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: .bach/workspace/logbook.md
