name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2

      - name: 'Build with Bach'
        uses: sormuras/bach/.github/action@main

      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            .bach/workspace/logbook.md
            .bach/workspace/modules
