name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2

      - name: 'Set up Java'
        uses: actions/setup-java@v1
        with:
          java-version: 16-ea

      - name: 'Set up version string'
        run: |
          SHA7=$(echo "${{ github.sha }}" | cut -c1-7)
          VERSION="1-ea+${SHA7}"
          echo "VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
          
      - name: 'Initialize Bach'
        run: jshell https://bit.ly/bach-init

      - name: 'Build with Bach'
        run: .bach/bin/bach --project-version ${{ env.VERSION }} --project-targets-java 9 build

      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ env.VERSION }}
          path: |
            .bach/workspace/logbook.md
            .bach/workspace/modules

      - name: 'Release early-access build'
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: 'early-access'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: "Simplicissimus ${{ env.VERSION }}"
          files: |
            .bach/workspace/modules/*.jar
