name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2

      - name: 'Set up Java'
        uses: actions/setup-java@v1
        with:
          java-version: 16-ea

      - name: 'Set up version string'
        run: |
          SHA7=$(echo "${{ github.sha }}" | cut -c1-7)
          VERSION="1-ea+${SHA7}"
          echo "VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}

      - name: 'Build with Bach'
        run: |
          jshell \
          -R-Dbach.project.version=${{ env.VERSION }} \
          -R-Dbach.project.main.release=9 \
          -R-Dbach.project.main.jarslug=early-access \
          https://github.com/sormuras/bach/releases/download/16.0.2/build.jsh

      - name: 'Upload build artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-build-${{ env.VERSION }}
          path: |
            .bach/workspace/modules

      - name: 'Release early-access build'
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: 'early-access'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: "Simplicissimus ${{ env.VERSION }}"
          files: |
            .bach/workspace/modules/*.jar
