name: Release

on:
  release:
    types: released

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2

      - name: 'Set up JDK 15'
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: 'Print release event information'
        run: |
          echo "github.actor=${{ github.actor }}"
          echo "github.sha=${{ github.sha }}"
          echo "github.event.release.tag_name=${{ github.event.release.tag_name }}"
          echo "github.event.release.upload_url=${{ github.event.release.upload_url }}"
          echo ::set-env name=VERSION::${{ github.event.release.release.tag_name }}

      - name: 'Get release information'
        id: get_release
        uses: bruceadams/get-release@v1.2.1

      - name: 'Build with Bach'
        run: jshell -R-Dbach.project.name='simplicissimus' -R-Dbach.project.version="${{ steps.get_release.outputs.tag_name }}" -R-Dbach.javac.release='9' https://sormuras.de/bach/build

      - name: 'Upload module com.github.sormuras.simplicissimus'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: .bach/workspace/modules/com.github.sormuras.simplicissimus@${{ steps.get_release.outputs.tag_name }}.jar
          asset_name: com.github.sormuras.simplicissimus@${{ steps.get_release.outputs.tag_name }}.jar
          asset_content_type: application/java-archive
